### PR TITLE
Create phony project

### LINKED ISSUE #9: JosephWebster Recommendations for Thornton, CO
# Thornton, Colorado
- [x] create branch
- [x] add a file
- [x] open pull request
- [x] collaborate
- [x] get +1
- [x] ship it

@alephzed @whitbeck @bnaqica Say what??!!

### PR DESCRIPTION
**Pull request by JosephWebster**
Resolves #9 
## Swell template for JosephWebster-Hometown

@alephzed @whitbeck @bnaqica

### CODE REVIEW

**Comment by bnaqica** [comment]
Sweet 👍

**Comment by whitbeck** [comment]
☎️ y

**Comment by alephzed** [comment]
🐎 🎱 👻 🏃

**Comment by srreanu** [comment]
It looks good Joe.

**Comment by JosephWebster** [comment]
@bnaqica 
It compiles. Ship it.

**Comment by srreanu** [comment]
👍

**Pull request merged**
