### PR TITLE
create a supputuri hometown file

### LINKED ISSUE #6: GithubTeacher's recommendations for Srinivasa, Upputuri, CO

### PR DESCRIPTION
**Pull request by supputuri**
Resolves #6 
## What do you want to know?
- Do you like any specific types of food?
- Any types of activities you enjoy?

@bmdangol @baryal

### CODE REVIEW

**Comment by FalconDelmi** [comment]
What's the name of your hometown?

**Comment by bmdangol** [comment]
Good Job!!!!
I ❤️  it
@supputuri  @baryal @phustondva @vvanaparthi 

> Do you like any specific types of food?
> Yes I do.
> 
> Any types of activities you enjoy?

Playing TT.

**Comment by JosephWebster** [comment]
> Do you like any specific types of food?
> `Absolutely`
> 
> Any types of activities you enjoy?
> `Poker`

**Comment by phustondva** [comment]
:+1:

**Pull request merged**
