### PR TITLE
Create a githubdmgross144-Centennial file

### LINKED ISSUE #5: dmgross144's recommendations for Centennial, CO

### PR DESCRIPTION
**Pull request by dmgross144**
Resolves #5 
## What do you want to know?
- Do you like any specific types of food?
- Any types of activities you enjoy?

@whitbeck @baryal

### CODE REVIEW

**Comment by whitbeck** [comment]
> Do you like any specific types of food?

Spicy!!!

**Comment by cheqmate** [comment]
👎

**Comment by dmgross144** [comment]
I suppose I might need to suggest an alkaselzer with the spicy food recommendation

@cheqmate

**Comment by cheqmate** [comment]
👍

**Comment by dmgross144** [comment]
fff

**Pull request merged**
