### PR TITLE
create phustondva-hometown file

### LINKED ISSUE #19: phustondva recommendations for Podunk, CO
# 
- [x] create a branch
- [x] add a file 
- [x] commit the file 
- [x] open a pull request 
- [x] talk to team 
- [x] get a :+1: 
- [ ] merge pull request

add a file

### PR DESCRIPTION
**Pull request by phustondva**
Resolves #19 
## what do you want to know

@supputuri @bmdangol @whitbeck

### CODE REVIEW

**Comment by divanathan** [comment]
hi

**Comment by phustondva** [comment]
test comment

**Comment by bnaqica** [comment]
Another comment 💯

**Comment by FalconDelmi** [comment]
Would live to visit hometown, but wondering how best to travel there. Any ideas?

**Comment by dmgross144** [comment]
:+1:

**Comment by bmdangol** [comment]
👍 Looks good.

**Pull request merged**
