### PR TITLE
B12345 - MT - do stuffs for ui peeps.

### LINKED ISSUE #7: kkw-davita recommendations for fantasyland

### PR DESCRIPTION
**Pull request by kkw-davita**
not what, but why.

We changed requirements based on meeting with PO on 4/1.

Fixes #7 

@alephzed

### CODE REVIEW

**Comment by divanathan** [comment]
hi

**Comment by cheqmate** [comment]
Freaking me out man, the naming of your issue was quite disturbing!

**Comment by srreanu** [comment]
🔵

**Comment by cheqmate** [comment]
👍

**Pull request merged**
