### PR TITLE
Create a cheqmate-hometown file

### LINKED ISSUE #10: cheqmate's recommendations for Kansas City, MO
# Kansask City, MO
- [x]  Create a branch
- [x] Add a file
- [x] Comment the file
- [ ] Collaborate with my team
- [ ] Get a 👍 
- [ ] :shipit: Merge the pull request

@alephzed @divanathan Hmmmmm, think we're using these features here?

### PR DESCRIPTION
**Pull request by cheqmate**
Resolves #10 

Don't touch my stuff man! This is my file, not yours and you're not the boss of me!

@divanathan @alephzed

### CODE REVIEW

**Comment by divanathan** [comment]
hi

**Comment by whitbeck** [comment]
Share your file!

🍺

**Comment by kkw-davita** [comment]
sucks. rewrite it.

**Comment by alephzed** [comment]
🎿 🍻

**Comment by srreanu** [comment]
😆

**Comment by alephzed** [comment]
👍

**Pull request merged**
